import React from 'react'
import { describe, it, expect, vi, afterEach } from 'vitest'
import { render, screen, fireEvent, waitFor, cleanup } from '@testing-library/react'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { ConfirmProvider } from '../../components/ConfirmProvider'
import TargetsPage from '../Targets'

// Single fetch stub that supports both general and plugin-mode tests
vi.stubGlobal('fetch', vi.fn(async (url: string, init?: RequestInit) => {
  const u = url.toString()
  if (u.endsWith('/plugins/')) {
    return new Response(JSON.stringify([
      { key: 'pihole', name: 'Pi-hole', version: '1.0.0' },
      { key: 'postgres', name: 'Postgres', version: '1.0.0' },
    ]), { status: 200 })
  }
  if (u.endsWith('/targets/')) {
    if (init?.method === 'POST') {
      const body = JSON.parse(init.body as string)
      return new Response(JSON.stringify({
        id: 2,
        name: body.name ?? 'N',
        slug: body.slug ?? (body.name ? body.name.toLowerCase() : 'n'),
        plugin_name: body.plugin_name ?? 'pihole',
        plugin_config_json: body.plugin_config_json ?? '{}',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      }), { status: 201 })
    }
    return new Response(JSON.stringify([]), { status: 200 })
  }
  return new Response('not found', { status: 404 })
}))

function wrapper(children: React.ReactNode) {
  const qc = new QueryClient()
  return <QueryClientProvider client={qc}><ConfirmProvider>{children}</ConfirmProvider></QueryClientProvider>
}

describe('TargetsPage', () => {
  afterEach(() => cleanup())
  it('renders list and create form', async () => {
    render(wrapper(<TargetsPage />))
    await screen.findByText('Targets')
    // Open create form first
    fireEvent.click(screen.getByLabelText('Add Target'))
    fireEvent.change(screen.getByLabelText('Name'), { target: { value: 'N' } })
    // Slug is generated by backend; no slug field in UI anymore
    const select = await screen.findByLabelText('Plugin')
    fireEvent.change(select, { target: { value: 'pihole' } })
    fireEvent.submit(screen.getByText('Create').closest('form')!)
    await waitFor(() => expect(fetch).toHaveBeenCalled())
  })

  it('creates a target in plugin mode', async () => {
    render(wrapper(<TargetsPage />))
    // Open create form first (avoid ambiguous heading match)
    const addBtn = await screen.findByLabelText('Add Target')
    fireEvent.click(addBtn)
    fireEvent.change(await screen.findByLabelText('Plugin'), { target: { value: 'pihole' } })
    fireEvent.change(screen.getByLabelText('Name'), { target: { value: 'Pi-hole' } })
    fireEvent.change(screen.getByLabelText('Plugin Config JSON'), { target: { value: '{"foo":"bar"}' } })
    fireEvent.submit(screen.getByText('Create').closest('form')!)
    await waitFor(() => expect(fetch).toHaveBeenCalled())
  })
})


