import React from 'react'
import { describe, it, expect, vi } from 'vitest'
import { render, screen, fireEvent, waitFor } from '@testing-library/react'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { ConfirmProvider } from '../components/ConfirmProvider'
import TargetsPage from './Targets'

vi.stubGlobal('fetch', vi.fn(async (url: string, init?: RequestInit) => {
  if (url.endsWith('/plugins/')) {
    return new Response(JSON.stringify([
      { key: 'pihole', name: 'Pi-hole', version: '1.0.0' },
      { key: 'postgres', name: 'Postgres', version: '1.0.0' },
    ]), { status: 200 })
  }
  if (url.endsWith('/targets/')) {
    if (init?.method === 'POST') {
      return new Response(JSON.stringify({
        id: 1, name: 'N', slug: 'n', plugin_name: 'pihole', plugin_config_json: '{}', created_at: new Date().toISOString(), updated_at: new Date().toISOString()
      }), { status: 201 })
    }
    return new Response(JSON.stringify([]), { status: 200 })
  }
  return new Response('not found', { status: 404 })
}))

function wrapper(children: React.ReactNode) {
  const qc = new QueryClient()
  return <QueryClientProvider client={qc}><ConfirmProvider>{children}</ConfirmProvider></QueryClientProvider>
}

describe('TargetsPage', () => {
  it('renders list and create form', async () => {
    render(wrapper(<TargetsPage />))
    await screen.findByText('Targets')
    // Open create form first
    fireEvent.click(screen.getByLabelText('Add Target'))
    fireEvent.change(screen.getByLabelText('Name'), { target: { value: 'N' } })
    // Slug is generated by backend; no slug field in UI anymore
    const select = await screen.findByLabelText('Plugin')
    fireEvent.change(select, { target: { value: 'pihole' } })
    fireEvent.submit(screen.getByText('Create').closest('form')!)
    await waitFor(() => expect(fetch).toHaveBeenCalled())
  })
})


